obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.35, -0.3], [0.35, 0.3], [-0.35,0.3], [-0.35, -0.3]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.5

obstacle_layer:
  observation_sources: scan_front scan_rear
  scan_front: {sensor_frame: summit_xl_front_laser_link, data_type: LaserScan, topic: /summit_xl/front_laser/scan, marking: true, clearing: true, expected_update_rate: 0.1, min_obstacle_height: 0.0, max_obstacle_height: 0.5}
  scan_rear: {sensor_frame: summit_xl_rear_laser_link, data_type: LaserScan, topic: /summit_xl/rear_laser/scan, marking: true, clearing: true, expected_update_rate: 0.1, min_obstacle_height: 0.0, max_obstacle_height: 0.5}
