local_costmap:
   global_frame: /summit_xl_odom
   robot_base_frame: /summit_xl_base_footprint
   update_frequency: 5.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 7.0
   height: 7.0
   resolution: 0.05
   transform_tolerance: 1.0
