obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[0.35, -0.3], [0.35, 0.3], [-0.35,0.3], [-0.35, -0.3]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.2

obstacle_layer:
  observation_sources: scan
  scan: {sensor_frame: summit_xl_front_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
