planner_frequency: 1.0
planner_patience: 2.0

controller_frequency: 10.0
controller_patience: 3.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

recovery_behavior_enabled: true
shutdown_costmaps: false

recovery_behaviors:
  - name: 'super_conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

super_conservative_reset:
  reset_distance: 5.0
  layer_names: ["obstacle_laser_layer"]

conservative_reset:
  reset_distance: 3.0
  layer_names: ["obstacle_laser_layer"]

aggressive_reset:
  reset_distance: 1.84
layer_names: ["obstacle_laser_layer"]
